mkbootimg: script must handle errors raised by gen-os.sh
BZ: 32379

Change-Id: Ie22446b6dca881e987e820d64b326daed57e2b44
Signed-off-by: Laurent Kappel <laurentx.kappel@intel.com>
Reviewed-on: http://android.intel.com:8080/47690
Reviewed-by: Mahe, Erwan <erwan.mahe@intel.com>
Reviewed-by: Alberdi, IonX <ionx.alberdi@intel.com>
Tested-by: Letessier, ChristopheX <christophex.letessier@intel.com>
Reviewed-by: Monnier, Olivier <olivier.monnier@intel.com>
Reviewed-by: buildbot <buildbot@intel.com>
Tested-by: buildbot <buildbot@intel.com>

diff --git a/mkbootimg b/mkbootimg
--- a/mkbootimg
+++ b/mkbootimg
@@ -103,11 +103,29 @@ TOP=`pwd`
 # stitch binary
 
 UPPER_TYPE=`echo $TYPE|tr '[:lower:]' '[:upper:]'`
-./device/intel/PRIVATE/xfstk-stitcher/gen-os.sh --input ${TOP}/${UNSIGNED_OUT} --output ${TOP}/${OUT} --xml ${UPPER_TYPE}_OTA.XML
+TMPFILE=`mktemp /tmp/gen-os.tmp.XXX`
+GEN_OS_APP="device/intel/PRIVATE/xfstk-stitcher/gen-os.sh"
+
+GEN_OS_APP_ARGS="--input ${TOP}/${UNSIGNED_OUT} --output ${TOP}/${OUT} --xml ${UPPER_TYPE}_OTA.XML"
+./${GEN_OS_APP} ${GEN_OS_APP_ARGS} 2>${TMPFILE}
+if [ $? -ne 0 ]; then
+	echo -e  "./${GEN_OS_APP} ${GEN_OS_APP_ARGS}: error\n$(cat ${TMPFILE})" >&2
+	rm -f ${TMPFILE}
+	exit 1
+fi
+rm -f ${TMPFILE}
+
 # only generate POS version for those types of images
 case "$TYPE" in
     combined|fastboot|droidboot)
-            ./device/intel/PRIVATE/xfstk-stitcher/gen-os.sh --input ${TOP}/${UNSIGNED_OUT} --output ${TOP}/${OUT}.POS.bin --xml ${UPPER_TYPE}.XML
+            GEN_OS_APP_ARGS="--input ${TOP}/${UNSIGNED_OUT} --output ${TOP}/${OUT}.POS.bin --xml ${UPPER_TYPE}.XML"
+            ./${GEN_OS_APP} ${GEN_OS_APP_ARGS} 2>${TMPFILE}
+			if [ $? -ne 0 ]; then
+				echo -e  "./${GEN_OS_APP} ${GEN_OS_APP_ARGS}: error\n$(cat ${TMPFILE})" >&2
+				rm -f ${TMPFILE}
+				exit 1
+			fi
+			rm -f ${TMPFILE}
             ;;
 esac
 
