mkbootimg: Use the generated bootstub
BZ: 98212

Take the bootstub generated from sources instead of the
pre-built binary blobs, and remove the binary blobs.

Add a new command line option to mkbootimg to pass the
bootstub file to use.

Use 0 as silicon type to rely on bootstub's SoC
auto-detect routine.

Clean-up the stitch.sh shell script to give accurate
and consistent help message.

Change-Id: I264aee681e09a1daa893d089f91ba016ef727d47
Signed-off-by: Olivier Fourdan <olivier.fourdan@intel.com>
Reviewed-on: http://android.intel.com:8080/100250
Reviewed-by: Fert, Laurent <laurent.fert@intel.com>
Reviewed-by: Tinelli, Vincent <vincent.tinelli@intel.com>
Reviewed-by: cactus <cactus@intel.com>
Tested-by: cactus <cactus@intel.com>

diff --git a/mkbootimg b/mkbootimg
--- a/mkbootimg
+++ b/mkbootimg
@@ -4,8 +4,8 @@ PLTTYPE=MFDC0
 SPIFLAG=0
 
 TEMP=`getopt \
-         -o c:r:k:o:p:t:s:f:y: \
-         --long cmdline:,ramdisk:,kernel:,output:,product:,type:,sign-with:,spi-flag:,plt-type: \
+         -o c:r:k:o:p:t:s:b:f:y: \
+         --long cmdline:,ramdisk:,kernel:,output:,product:,type:,sign-with:,bootstub:,spi-flag:,plt-type: \
          -n '$0' \
          --  "$@"`
 
@@ -18,6 +18,7 @@ while true ; do
         --kernel) BZIMAGE=$2; shift 2;;
         --output) OUT=$2; shift 2;;
         --product) BOARD=$2; shift 2;;
+        --bootstub) BOOTSTUB=$2; shift 2;;
         --sign-with) SIGN_WITH=${2,,}; shift 2;;
         --type) TYPE=$2; shift 2;;
         --spi-flag) SPIFLAG=$2; shift 2;;
@@ -45,24 +46,6 @@ fi
 UNSIGNED_OUT=${TARG}/${IMGNAME}.unsigned
 CMDLINE_FILE=${TARG}/${IMGNAME}_cmdline
 echo $CMDLINE > $CMDLINE_FILE
-BOOTSTUB=vendor/intel/support/bootstub
-
-
-if [[   "$BOARD" == "saltbay" \
-     || "$BOARD" == "moor_hvp" \
-     || "$BOARD" == "moor_sle" \
-     || "$BOARD" == "crc_hvp" \
-   ]]; then
-    BOOTSTUB=${BOOTSTUB}_mrfl
-fi
-
-if [[   "$BOARD" == "baylake" \
-     || "$BOARD" == "byt_t_ffrd10" \
-     || "$BOARD" == "byt_t_ffrd8" \
-     || "$BOARD" == "byt_m_crb" \
-   ]]; then
-    BOOTSTUB=${BOOTSTUB}_byt
-fi
 
 if [ ! -e ${BZIMAGE} ]; then
     echo "error: bzImage file ${BZIMAGE} does not exist"
@@ -79,6 +62,11 @@ if [ ! -e "${CMDLINE_FILE}" ]; then
     exit 1
 fi
 
+if [ -z "${BOOTSTUB}" ]; then
+    echo "error: bootstub file not provided"
+    exit 1
+fi
+
 if [ ! -e ${BOOTSTUB} ]; then
     echo "error: bootstub file ${BOOTSTUB} does not exist"
     exit 1
@@ -92,8 +80,8 @@ fi
 echo "Creating image \`${OUT}'for FSTK stitching..."
 
 rm -f ${UNSIGNED_OUT}
-# 0: SPI0(Moorestown) 1: SPI1(Medfield)
-SILICON=1
+# 0:auto-detect based on SoC, 1:SPI1 (Penwell, Cloverview), 2:SPI2 (Tangier, Anniedale)
+SILICON=0
 ./vendor/intel/support/stitch.sh ${CMDLINE_FILE} ${BOOTSTUB} ${BZIMAGE} ${INITRD} ${SPIFLAG} ${SILICON} ${UNSIGNED_OUT}
 
 if [ "0" -ne "$?" ]; then
