one-time-install downloads Java directly from web site
BZ: 19337

The Java install under Ubuntu was deactivated. The best solution is to
download the Java SE 6 install file directly from web site.

I replaced "apt-get install" with "wget". "wget" uses environment
variables to get the proxy setting. sudo does not pass the environment
by default. To get the proxy settings you need to either use "sudo -E"
or run the script from a root login.

To run this script:
    sudo -E one-time-setup

Change-Id: I84f15283a10beb3de11f524b542588ae7e3a4f60
Signed-off-by: henry tieman <henry.w.tieman@intel.com>
Reviewed-on: http://android.intel.com:8080/31109
Reviewed-by: Linn, David <david.linn@intel.com>
Tested-by: Linn, David <david.linn@intel.com>
Reviewed-by: Mahe, Erwan <erwan.mahe@intel.com>
Reviewed-by: Tian, XiaojunX <xiaojunx.tian@intel.com>
Reviewed-by: Peng, PengX <pengx.peng@intel.com>
Reviewed-by: Peng, BoX <box.peng@intel.com>
Reviewed-by: buildbot <buildbot@intel.com>
Tested-by: buildbot <buildbot@intel.com>

diff --git a/one-time-setup b/one-time-setup
--- a/one-time-setup
+++ b/one-time-setup
@@ -32,21 +32,53 @@ sudo apt-get install git-core gnupg flex bison gperf build-essential \
  lib32ncurses5-dev ia32-libs x11proto-core-dev libx11-dev \
  lib32readline5-dev lib32z-dev eclipse tofrodos
 
+sudo apt-get install libxml-simple-perl
+
 sudo ln -s /usr/bin/fromdos /usr/local/bin/dos2unix
 
 # step 2 - install valgrind - skipped
 
 # step 3 - download java 6 jdk
+TMP_DIR=/tmp/java_install
+JAVA_URL="http://download.oracle.com/otn-pub/java/jdk/6u30-b12"
+JAVA_BIN="jdk-6u30-linux-x64.bin"
+
+if [ ! -d ${TMP_DIR} ]; then
+    mkdir ${TMP_DIR}
+fi
+
+wget -t 10 -P ${TMP_DIR} ${JAVA_URL}/${JAVA_BIN}
+
+if [ $? -ne 0 ]; then
+    echo "ERROR: wget failure"
+    echo "   this script should be executed as root"
+    echo "   please check wget proxy settings and retry"
+    exit -1
+fi
+
 # step 4 - change permission on jdk
+chmod 755 ${TMP_DIR}/${JAVA_BIN}
+
 # step 5 - install jdk
+JAVA_BASE=/usr/lib/jvm
+JAVA_DIR=jdk1.6.0_30
+JAVA_LINK=java-6-sun
+if [ ! -d ${JAVA_BASE} ]; then
+    mkdir -p ${JAVA_BASE}
+fi
+cd ${JAVA_BASE}
 
-sudo add-apt-repository "deb http://archive.canonical.com/ lucid partner"
-sudo add-apt-repository "deb-src http://archive.canonical.com/ubuntu lucid partner"
-sudo apt-get update
-sudo apt-get install sun-java6-jdk
-sudo update-java-alternatives -s java-6-sun
+sh ${TMP_DIR}/${JAVA_BIN} -noregister
 
-# step 6 - setenvironment variables for java
+if [ -h ${JAVA_BASE}/${JAVA_LINK} ]; then
+    rm ${JAVA_BASE}/${JAVA_LINK}
+fi
+
+ln -s ${JAVA_BASE}/${JAVA_DIR} ${JAVA_BASE}/${JAVA_LINK}
+
+rm -rf ${TMP_DIR}
+
+# step 6 - set environment variables for java
 
 JAVA_HOME=/usr/lib/jvm/java-6-sun
 ANT_HOME=/usr/share/ant
